
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: property_finder_development
  username: postgres
  password: 1234
  host: localhost
  port: 5432
test:
  <<: *default
  database: property_finder_test
  username: postgres
  password: 1234
  host: localhost
  port: 5432


production:
  primary: &primary_production
    <<: *default
    database: property_finder_production
    username: postgres
    password: <%= ENV["PROPERTY_FINDER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: property_finder_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: property_finder_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: property_finder_production_cable
    migrations_paths: db/cable_migrate
